import JSZip from 'jszip';
import { DesignTree } from '../types/models';
import { generateRustCode, generateCargoToml } from './codeGenerator';

/**
 * プロジェクトをZipファイルとしてダウンロード
 */
export const exportProjectAsZip = async (
  projectName: string,
  designData: DesignTree
): Promise<void> => {
  const zip = new JSZip();

  // プロジェクト名をサニタイズ
  const sanitizedName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '_')
    .replace(/^[0-9]/, '_$&');

  // プロジェクトフォルダを作成
  const projectFolder = zip.folder(sanitizedName);
  if (!projectFolder) {
    throw new Error('Failed to create project folder');
  }

  // src フォルダを作成
  const srcFolder = projectFolder.folder('src');
  if (!srcFolder) {
    throw new Error('Failed to create src folder');
  }

  // main.rs を生成
  const mainRs = generateRustCode(designData);
  srcFolder.file('main.rs', mainRs);

  // Cargo.toml を生成
  const cargoToml = generateCargoToml(projectName);
  projectFolder.file('Cargo.toml', cargoToml);

  // .gitignore を追加
  const gitignore = `/target
Cargo.lock
`;
  projectFolder.file('.gitignore', gitignore);

  // README.md を追加
  const readme = `# ${projectName}

A TUI application generated by Tuify.

## Requirements

- Rust (1.70.0 or later)

## Build & Run

\`\`\`bash
cargo run
\`\`\`

Press 'q' to quit the application.

## Generated with

[Tuify](https://github.com/your-repo/tuify) - Rust TUI Design Platform
`;
  projectFolder.file('README.md', readme);

  // Zipを生成してダウンロード
  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${sanitizedName}.zip`);
};

/**
 * Blobをファイルとしてダウンロード
 */
const downloadBlob = (blob: Blob, filename: string): void => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Rustコードのみをダウンロード
 */
export const downloadRustCode = (
  projectName: string,
  designData: DesignTree
): void => {
  const code = generateRustCode(designData);
  const blob = new Blob([code], { type: 'text/plain' });
  downloadBlob(blob, 'main.rs');
};
